---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-fetcher
  namespace: efsearch
  labels:
    app: efs-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-fetcher
  template:
    metadata:
      labels:
        app: efs-fetcher
    spec:
      containers:
      - name: efs-fetcher
        image: registry.owny.cz/efsearch-backend
        command: ["/efsearch/entrypoint.sh"]
        args: ["fetcher"]
        env:
        - name: POSTGRES_USER
          value: efs_db_user
        - name: POSTGRES_PASSWORD
          value: efs_db_user_pwd
        - name: POSTGRES_DB
          value: efsearch
        - name: POSTGRES_HOST
          value: efs-db.efsearch.svc
        - name: NATS_HOST
          value: nats://efs-nats.efsearch.svc:4222
        - name: LOGGING_LEVEL_APP
          value: WARNING
