---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-nats
  namespace: efsearch
  labels:
    app: efs-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-nats
  template:
    metadata:
      labels:
        app: efs-nats
    spec:
      containers:
      - name: efs-nats
        image: nats:2.1.8
        ports:
        - containerPort: 4222

---
apiVersion: v1
kind: Service
metadata:
  name: efs-nats
  namespace: efsearch
spec:
  selector:
    app: efs-nats
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
